 /*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HomePage.java
 *
 * Created on 5 Dec, 2016, 7:18:48 PM
 */
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author Jayanthi
 */
public class LoginPage extends javax.swing.JFrame {
Connection conn1=null;
Statement st=null;
ResultSet rset=null;
    /** Creates new form HomePage */
    public LoginPage() {
        initComponents();
try{
Class.forName("java.sql.DriverManager");
conn1=DriverManager.getConnection("jdbc:mysql://localhost/IPProject7S","root","");
        }
catch(Exception e){
JOptionPane.showMessageDialog(null,"ERROR!"+e.getMessage());
       }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("USERNAME  :");

        jLabel2.setText("PASSWORD :");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ADMIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("RECEPTIONIST");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("SUPERVISOR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(27, 27, 27)
                        .addComponent(jButton2)
                        .addGap(27, 27, 27)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField1))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try{
st=conn1.createStatement();
String username=jTextField1.getText();
jTextField1.setText(username);
if(jTextField1.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Enter Username");
}
String password=jPasswordField1.getText();
if(jPasswordField1.getText().equals("")){
JOptionPane.showMessageDialog(null,"Enter Password");
}
String SQL="SELECT * FROM LOGIN WHERE USERNAME="+"'"+username+"'";
rset=st.executeQuery(SQL);
while(rset.next()){
    if((rset.getString("DESIGNATION").equals("RECEPTIONIST"))&&(rset.getString("PASSWORD").equals(password))){
      this.setVisible(false);
      new Receptionist(conn1,this).setVisible(true);
        }
    else if((rset.getString("DESIGNATION").equals("ADMIN"))||(rset.getString("DESIGNATION").equals("SUPERVISOR"))){
      JOptionPane.showMessageDialog(null,"You cannot login ! You are not a Receptionist !");
        }
    else{
     JOptionPane.showMessageDialog(null,"Incorrect Password !");
       }
     }
  }
catch(Exception e){
JOptionPane.showMessageDialog(null,"ERROR!"+e.getMessage());
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
st=conn1.createStatement();
String username=jTextField1.getText();
jTextField1.setText(username);
if(jTextField1.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Enter Username");
}
String password=jPasswordField1.getText();
if(jPasswordField1.getText().equals("")){
JOptionPane.showMessageDialog(null,"Enter Password");
}
String SQL="SELECT * FROM LOGIN WHERE USERNAME="+"'"+username+"'";
rset=st.executeQuery(SQL);
while(rset.next()){
    String Password=rset.getString("PASSWORD");
    if((rset.getString("DESIGNATION").equals("ADMIN"))&&(rset.getString("PASSWORD").equals(password))){
      this.setVisible(false);
      new Admin(conn1,this).setVisible(true);
        }
    else if((rset.getString("DESIGNATION").equals("RECEPTIONIST"))||(rset.getString("DESIGNATION").equals("SUPERVISOR"))){
      JOptionPane.showMessageDialog(null,"You cannot login ! You are not an Admin !");
        }
 else{
     JOptionPane.showMessageDialog(null,"Incorrect Password !");
 }
     }
  }
catch(Exception e){
JOptionPane.showMessageDialog(null,"ERROR!"+e.getMessage());
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try{
st=conn1.createStatement();
String username=jTextField1.getText();
jTextField1.setText(username);
if(jTextField1.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Enter Username");
}
String password=jPasswordField1.getText();
if(jPasswordField1.getText().equals("")){
JOptionPane.showMessageDialog(null,"ENTER PASSWORD");
}
String SQL="SELECT * FROM LOGIN WHERE USERNAME="+"'"+username+"'";
rset=st.executeQuery(SQL);
while(rset.next()){
    if((rset.getString("DESIGNATION").equals("SUPERVISOR"))&&(rset.getString("PASSWORD").equals(password))){
      this.setVisible(false);
      new Supervisor(conn1,this).setVisible(true);
        }
    else if((rset.getString("DESIGNATION").equals("RECEPTIONIST"))||(rset.getString("DESIGNATION").equals("ADMIN"))){
      JOptionPane.showMessageDialog(null,"You cannot login ! You are not a Supervisor !");
        }
    else{
     JOptionPane.showMessageDialog(null,"Incorrect Password !");
         }
     }
  }                    
catch(Exception e){
JOptionPane.showMessageDialog(null,"ERROR!"+e.getMessage());
}
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
